from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.lib.colors import HexColor, black
from io import BytesIO
from models import Song

def sanitize_filename(title: str, key: str) -> str:
    """Create safe filename from song title and key"""
    # Remove/replace unsafe characters
    safe_title = "".join(c if c.isalnum() or c in (' ', '-') else '-' for c in title)
    # Replace spaces with dashes
    safe_title = safe_title.replace(' ', '-')
    # Remove consecutive dashes
    while '--' in safe_title:
        safe_title = safe_title.replace('--', '-')
    # Remove leading/trailing dashes
    safe_title = safe_title.strip('-')

    return f"{safe_title}-{key}.pdf"

def generate_song_pdf(song: Song, transposed_key: str = None, transposed_chords: str = None) -> BytesIO:
    """
    Generate PDF for a song with chord sheet.

    Args:
        song: Song model instance
        transposed_key: Target key if transposed (optional)
        transposed_chords: Transposed chord text (optional)

    Returns:
        BytesIO buffer containing PDF
    """
    # Create buffer
    buffer = BytesIO()

    # Create canvas
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    # Margins
    margin = 0.75 * inch
    x = margin
    y = height - margin

    # Colors
    gold = HexColor('#f0c040')
    gray = HexColor('#666666')

    # Title
    c.setFont("Helvetica-Bold", 18)
    c.setFillColor(black)
    c.drawString(x, y, song.title)
    y -= 30

    # Metadata line
    c.setFont("Helvetica", 10)
    c.setFillColor(gray)

    key_display = transposed_key or song.original_key
    if transposed_key and transposed_key != song.original_key:
        key_text = f"Key: {transposed_key} (transposed from {song.original_key})"
    else:
        key_text = f"Key: {song.original_key}"

    metadata = f"Language: {song.language} | Category: {song.category} | {key_text}"
    c.drawString(x, y, metadata)
    y -= 20

    # Horizontal line
    c.setStrokeColor(gray)
    c.setLineWidth(0.5)
    c.line(x, y, width - margin, y)
    y -= 30

    # Chords section
    c.setFont("Courier", 11)
    c.setFillColor(black)

    # Use transposed chords if provided, otherwise original
    chord_text = transposed_chords if transposed_chords else song.chords

    # Split into lines and render
    lines = chord_text.split('\n')
    line_height = 14

    for line in lines:
        # Check if we need a new page
        if y < margin + line_height:
            c.showPage()
            y = height - margin

            # Repeat title on new page (smaller)
            c.setFont("Helvetica-Bold", 12)
            c.setFillColor(gray)
            c.drawString(x, y, song.title)
            y -= 25

            c.setFont("Courier", 11)
            c.setFillColor(black)

        # Draw line
        c.drawString(x, y, line)
        y -= line_height

    # Footer
    c.setFont("Helvetica", 8)
    c.setFillColor(gray)
    footer_text = "Generated by Chord Manager"
    c.drawString(x, 0.5 * inch, footer_text)

    # Page number (if multiple pages)
    page_num = c.getPageNumber()
    if page_num > 1:
        c.drawString(width - margin - 50, 0.5 * inch, f"Page {page_num}")

    # Finalize PDF
    c.save()

    # Reset buffer position
    buffer.seek(0)

    return buffer
